enabled_locales: ["en", "vi"]
client:
  host: "localhost:3000"
users:
  name:
    maximum: 50
  email:
    maximum: 255
  password:
    minimum: 6
remember: "1"
perpage: 5
accept_picture: "image/jpeg,image/gif,image/png"
perpage_12: 12
quantity_product: 1
